# -*- coding: utf-8 -*-
"""Copy of Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164sfTfztW3R4UoRhc3kwhSsvWUxCCYHO
"""

import zipfile

zip_ref = zipfile.ZipFile('/content/hand_sign_dataset.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

print("Extracted!")

import os
os.listdir('/content/hand_sign_dataset')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Data generator
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train = train_datagen.flow_from_directory(
    '/content/hand_sign_dataset',
    target_size=(224,224),
    batch_size=16,
    class_mode='categorical',
    subset='training'
)

val = train_datagen.flow_from_directory(
    '/content/hand_sign_dataset',
    target_size=(224,224),
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

# Model
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(train.num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history = model.fit(train, validation_data=val, epochs=5)

# Save model
model.save("hand_sign_model.h5")

from google.colab import files
files.download("hand_sign_model.h5")

import os
os.listdir('/content/hand_sign_dataset')

import numpy as np
import cv2
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# Load model
model = load_model("hand_sign_model.h5")

labels = ["✊ Fist", "✌️ Peace", "👎 Thumbs Down", "👍 Thumbs Up"]

# Load image
img = cv2.imread('/content/test1.jpeg')

if img is None:
    print("Image not loaded!")
else:
    img_resized = cv2.resize(img, (224,224))
    img_norm = img_resized / 255.0
    img_input = np.reshape(img_norm, (1,224,224,3))

    pred = model.predict(img_input)
    class_id = np.argmax(pred)
    confidence = np.max(pred) * 100

    print("Prediction:", labels[class_id])
    print("Confidence:", confidence, "%")

    # Show image
    plt.imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
    plt.title(f"{labels[class_id]} ({confidence:.2f}%)")
    plt.axis('off')
    plt.show()

import numpy as np
import cv2
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# Load model
model = load_model("hand_sign_model.h5")

labels = ["✊ Fist", "✌️ Peace", "👎 Thumbs Down", "👍 Thumbs Up"]

# Load image
img = cv2.imread('/content/test1.jpeg')

if img is None:
    print("Image not loaded!")
else:
    img_resized = cv2.resize(img, (224,224))
    img_norm = img_resized / 255.0
    img_input = np.reshape(img_norm, (1,224,224,3))

    pred = model.predict(img_input)
    class_id = np.argmax(pred)
    confidence = np.max(pred) * 100

    print("Prediction:", labels[class_id])
    print("Confidence:", confidence, "%")

    # Show image
    plt.imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
    plt.title(f"{labels[class_id]} ({confidence:.2f}%)")
    plt.axis('off')
    plt.show()

import numpy as np
import cv2
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# Load model
model = load_model("hand_sign_model.h5")

labels = ["✊ Fist", "✌️ Peace", "👎 Thumbs Down", "👍 Thumbs Up"]

# Load image
img = cv2.imread('/content/test1.jpeg')

if img is None:
    print("Image not loaded!")
else:
    img_resized = cv2.resize(img, (224,224))
    img_norm = img_resized / 255.0
    img_input = np.reshape(img_norm, (1,224,224,3))

    pred = model.predict(img_input)
    class_id = np.argmax(pred)
    confidence = np.max(pred) * 100

    print("Prediction:", labels[class_id])
    print("Confidence:", confidence, "%")

    # Show image
    plt.imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
    plt.title(f"{labels[class_id]} ({confidence:.2f}%)")
    plt.axis('off')
    plt.show()